### PR TITLE
TC-989 Upload assets to S3

### PR DESCRIPTION
**Pull request by RohanM**
Currently we host our assets within the running docker container. When a new version is deployed, we lose old assets, which results in 404s for clients who have a cached version of the HTML. We'd like to solve this problem by serving our assets from S3 so that we can keep historical assets around.

This PR adds a deploy step `Upload assets` which uploads the assets to S3 and confirms that they're accessible publicly.

Once this step is running stably as part of the deploy process, we can point our apps at the S3 assets rather than the locally-served assets.

The script was developed in this draft PR: https://github.com/conversation/tc/pull/8905

Sample build (of draft PR): https://buildkite.com/conversation/tc/builds/51515#ca800f69-8465-4f71-bb3f-faf67d3743c5

TODO:

- [ ] Create buckets for all docker-deploy apps, for both staging and production

### CODE REVIEW

**Comment by nullobject** [comment]
This is awesome ❤️

**Comment by RohanM** [comment]
[Upload assets to S3 (docker-deploy)](https://trello.com/c/IPB5eY4b/113-upload-assets-to-s3-docker-deploy)

**Comment by RohanM** [comment]
I think that avoiding creating new buckets would be a good move overall.

The main tradeoff would be losing the separation between compiled assets and uploaded assets, and the potential for a clash or confusion between the two. A quick look at S3 in `theconversation-assets` shows that there are some old (2016) assets in the `assets/` directory, but otherwise there are no directory names in common between the uploaded and compiled assets. It would mean that when we're looking at S3 there'd be an additional question of "Where did this asset come from?", but it wouldn't be too hard to work out.

In return, we'd halve the number of buckets we need to manage, avoid needing to add more DNS entries, and have a simpler system overall.

**Comment by RohanM** [comment]
I've made the changes to follow the existing bucket names. That means that we're still using the `tc-` prefix on buckets other than `theconversation-assets` - though we might decide to do a bucket rename on jobs (if that's a feasible goal).

I also switched away from path-based bucket access, which is deprecated (see https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/).

**Comment by RohanM** [comment]
I've copied the changes to the test branch and run another build here:

https://buildkite.com/conversation/tc/builds/51740#eb39037c-ac9f-4a46-bd02-9d8c8b3efac6

**Comment by nullobject** [comment]
@RohanM Nice one :+1:

The latest build still appears to have the old bucket names:

`upload: ../../../../../../../tmp/tmp.lGFBSapxpT/assets/amp-logo-fr-c78b4a5b34cd2903edaa30e63572e767.svg to s3://tc-tc-compiled-assets-staging/amp-logo-fr-c78b4a5b34cd2903edaa30e63572e767.svg`

Am I looking in the wrong place?

**Comment by RohanM** [comment]
Sorry for the confusion - I put some code in to the test script to use the old bucket names after outputting the new name, so that we didn't upload a bunch of files to the staging bucket: https://github.com/conversation/tc/pull/8905/commits/d9a7b94498bc473518dabb0228093e539c210ef4

**Comment by RohanM** [comment]
Looking at that last build (the one that uploads to `theconversation-assets-staging`), we see it failing because that AWS user doesn't have access to that bucket. I'll write up a setup plan for AWS buckets and permissions now.

**Comment by nullobject** [comment]
@RohanM Nice work on this, merge whenever you're ready 👍

**Comment by RohanM** [comment]
The docker-deploy pipeline currently serves: counter, data-warehouse, jobs and sharejs. Of these, only jobs actually has assets, so if we deployed the code as it stood before, I believe it would have failed, breaking the deploy.

I've added a check for assets in the app, and if the directory `/app/public/assets` isn't found, the upload is skipped.

#### Test builds

- With assets: https://buildkite.com/conversation/tc/builds/51768#574c2c16-6b57-4b69-b3e2-9ae9568af1fd
- Without assets: https://buildkite.com/conversation/tc/builds/51769#65b90cbf-7eb7-4462-9f67-91c2a87ce343

The latter looks for assets in a directory that's not present, and thus skips the upload: https://github.com/conversation/tc/pull/8905/commits/0245f3c4ae6ef520d590b69b3695504efb2c9569

**Comment by RohanM** [comment]
#### Planned AWS setup

Grant permission to AWS `ci` user to buckets:

- `theconversation-assets`
- `theconversation-assets-staging`
- `tc-jobs-assets`
- `tc-jobs-assets-staging`

Do this by editing the policy `CIAssetsReadWriteAccess`.

Then remove the testing bucket `tc-tc-compiled-assets-staging`.

**Pull request merged**
