### PR TITLE
Refactor upload-assets step

### PR DESCRIPTION
**Pull request by nullobject**
I added an editor config file, so that we avoid ambiguities in the future. This PR refactors the upload-assets step to use two spaces for indentation (the same as our ruby and JS code style) and one blank line in between functions.

### CODE REVIEW

**Comment by nullobject** [comment]
[[Chore] Refactor upload-assets step](https://trello.com/c/MNYro6wv/153-chore-refactor-upload-assets-step)

**Comment by RohanM** [comment]
This looks good! I'm not sure where the editor config file is?

**Comment by nullobject** [comment]
@RohanM `.editorconfig`

**Comment by RohanM** [comment]
Cheers!

**Pull request merged**
