### PR TITLE
Notify slack after deploying

### PR DESCRIPTION
**Pull request by nullobject**
It probably makes more sense to notify slack after a successful deployment, rather than before deploying.

The reason I originally set it up to notify *before* was because it just reflected our manual process in slack. But @nickbrown mentioned that he only cares that something happened, not that something is about to happen. I totally agree.

### CODE REVIEW

**Comment by nullobject** [comment]
[Notify slack after deploying](https://trello.com/c/wwwkLRZC/10045-notify-slack-after-deploying)

**Comment by eleanorakh** [comment]
Good plan! 👍

**Comment by eleanorakh** [comment]
I can't merge this as I don't have write access, but 👍 from me to go ahead and hit the button.

**Comment by nullobject** [comment]
> I can't merge this as I don't have write access, but 👍 from me to go ahead and hit the button.

Oops, I fixed that. Thanks for letting me know 👍

**Comment by jameshill** [comment]
Would be possible to have both notification before deploy and the result after.

- deploying
- deployed/live
- failed/deploy etc

**Comment by nullobject** [comment]
> Would be possible to have both notification before deploy and the result after.

It certainly would. It could be a bit noisy, but I'm happy to try it.

**Comment by jameshill** [comment]
>> Would be possible to have both notification before deploy and the result after.
> 
> It certainly would. It could be a bit noisy, but I'm happy to try it.

I was thinking about this more today, and I'm kinda two sided about it...

I think you're right it'd be really noisy, and if it's just an announcement that a deploy is happening it doesn't really add much to the channel apart from noise...

So in that sense, I'm against announcing for the sake of it, as all the real information is whether it was a successful deploy, or if it failed to deploy.

However... if we got crafty about it, and identified which PRs were being deployed, and notified the creators/merges that their code was shipping then that could be interesting...

still probably a bit noisy, and also it's likely that the person who merged is probably clicking the unlock and shipping it... 

anyway, something we can iterate on at a later date.

**Comment by jameshill** [comment]
although.. i guess, all that information could be presented in the one notification anyway.
I'll shut my mouth now 😬

**Pull request merged**
